Vagrant::Config.run do |config|
  config.vm.box = "dev-vm-2.0"
  config.vm.box_url = "https://zeelot.s3.amazonaws.com/dev-vm-2.0-base.box"

  config.vm.forward_port("http", 80, 8080)
  config.vm.share_folder("hyla", "/var/www/hyla", "../", :owner => "vagrant")

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "cookbooks"

    # This provisions the server
    chef.add_recipe("vagrant_main")
  end
end